# Nome do workflow
name: Pipeline DevOps + IA
 
on:
  push:
    branches:
      - main
      - feature/**
 
  pull_request:
    branches:
      - main
 
jobs:
  pipeline:
 
    runs-on: ubuntu-latest
 
    permissions:
      contents: read
      issues: write
 
    steps:
 
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
 
      - name: Instalar dependências
        run: |
          pip install pytest
          pip install pytest-cov
          pip install groq
 
      # ==========================================================
      # ETAPA 1 - QUALITY GATE - teste
      # ==========================================================
      
 
      # - name: Testes + Quality Gate
      #   run: |
      #     pytest tests_alta/ \
      #       --cov=src_alta \
      #       --cov-report=json:coverage.json \
      #       --cov-fail-under=80 \
      #       -v
 
      # ==========================================================
      # ETAPA 2 - DEPLOY GATE COM IA
      # ==========================================================
 
      - name: Deploy Gate (Groq)
        id: deploy-gate
        run: python deploy/deploy_gate.py
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY || secrets.DEVOPS_SECRET || secrets.GROQCLOUD_API_KEY }}

      # ==========================================================
      # ETAPA 3 - CANARY DEPLOY
      # ==========================================================

      - name: Canary Deploy Simulator
        id: canary
        if: steps.deploy-gate.outcome == 'success'
        run: python deploy/canary_simulator.py

      # ==========================================================
      # ETAPA 4 - ROLLBACK - teste de chave
      # ==========================================================

      - name: Rollback + Relatório IA
        if: failure() && steps.canary.outcome == 'failure'
        run: python deploy/rollback_trigger.py
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY || secrets.DEVOPS_SECRET || secrets.GROQCLOUD_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
